name: 每日任务自动化

on:
  schedule:
    # 预约工作：每天的 6:15（UTC+8）对应 22:15 UTC
    - cron: '15 22 * * *'
    # 签到工作：每天的 8:31、8:35、8:55（UTC+8）对应 0:31、0:35、0:55 UTC
    - cron: '31,35,55 0,4,8 * * *'
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: 安装依赖
        run: pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
      - name: 运行预约脚本
        run: python reserve.py

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  
      - name: 安装依赖
        run: pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
      - name: 运行签到脚本
        run: python sign.py
